// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

/** Lee las variables soportando todos los nombres habituales sin romper. */
function readEnv() {
  const env = (typeof import.meta !== 'undefined' ? (import.meta as any).env : {}) || {};
  const proc = (typeof process !== 'undefined' ? process.env : {}) || {};
  const url =
    env.VITE_SUPABASE_URL ||
    proc.SUPABASE_URL ||
    env.SUPABASE_URL;
  const key =
    env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    env.VITE_SUPABASE_ANON_KEY ||
    proc.SUPABASE_PUBLISHABLE_KEY ||
    env.SUPABASE_PUBLISHABLE_KEY;
  return { url: url as string | undefined, key: key as string | undefined };
}

const { url: SUPABASE_URL, key: SUPABASE_PUBLISHABLE_KEY } = readEnv();

/** True si el cliente puede conectarse realmente con Supabase. */
export const isSupabaseConfigured = (): boolean =>
  Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

function buildClient() {
  if (!isSupabaseConfigured()) return null;
  return createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
    auth: {
      storage: typeof window !== 'undefined' ? window.localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

/**
 * Cliente real de Supabase. Será `null` si faltan las variables.
 * Úsalo SIEMPRE detrás de `if (isSupabaseConfigured())` o de la capa de
 * servicios en `src/services/` que ya gestiona el fallback local.
 */
export const supabaseClient = buildClient();

/**
 * Proxy de compatibilidad para código existente: NO rompe en import,
 * pero lanza un error claro si se intenta usar sin configurar.
 * Preferir `supabaseClient` o los servicios en nuevo código.
 */
export const supabase = new Proxy({} as NonNullable<ReturnType<typeof buildClient>>, {
  get(_t, prop, receiver) {
    if (!supabaseClient) {
      throw new Error(
        '[Supabase] No configurado. Faltan VITE_SUPABASE_URL / VITE_SUPABASE_ANON_KEY. ' +
          'Usa los servicios de src/services/ que tienen fallback local.',
      );
    }
    return Reflect.get(supabaseClient, prop, receiver);
  },
});

